### ISSUE TITLE
Mk1-2 Pod + Heat Shield + Paradock does not point aft first during reentry

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#107]
Observed by @Starwaster, confirmed by own experimentation.

When a Mk1-2 Pod equipped with an SDHI Heat Shield and Paradock reenters Kerbin's atmosphere, it begins swinging wildly instead of maintaining an aft-first orientation as the stock Heat Shield does.

We suspect that recent atmosphere changes in KSP 1.2.x (which stock parts already account for) may be the cause.

**Comment by sumghai** [comment]
@Starwaster initially suggested adding the `CoPOffset` and `CoLOffset` parameters from the stock 2.5m heat shield, but this had no significant effect.

However, adding the `ModuleLiftingSurface` definition does seem to help keep the pod reenter aft-first, although some tweaking will be needed since the pod and paradock still experience close-to-overheat warnings.

**Comment by Starwaster** [comment]
That's strange; when I changed the CoPOffset to 0, 1.1, 0, that did keep it oriented properly for me. I think I left CoLOffset alone. And I'm really not even liking that it's in there. Basically it moves the CoL to the bottom of the shield when it should be somewhere inside of it. But that's how stock does it and I'm really scratching my head as to why.

While mulling over this problem some things about stock aero have occurred to me that are really bothering me. If you look at a craft's overall center of pressure it's the sum of all CoP for all parts. But stack mounted parts occlude drag. Which does make a certain amount of sense except for the part where that means that it's cancelling out the CoP contribution of occluded parts.

I hope I'm misinterpreting something somewhere because that would mean that a command module type craft has its CoP entirely in the heatshield instead of the craft's centroid. It's no wonder we have to play games with the CoPOffset in the heatshields. That kind of tweak should be entirely unnecessary.

**Comment by sumghai** [comment]
I'll try removing the `CoLOffset` and see what happens.

**Comment by sumghai** [comment]
@Starwaster, I just tested the following:

`CoPOffset` only: pod orientation **unstable** during reentry

`CoPOffset` + `CoLOffset`: pod orientation **unstable** during reentry

`CoPOffset` + `ModuleLiftingSurface`: pod orientation stabilizes, but heatshield appears to tilt pod such that it is not fully pointing retrograde; pod and paradock experiencing overheat warnings

`CoPOffset` + `CoLOffset` + `ModuleLiftingSurface`: pod orientation stabilizes, but heatshield appears to tilt pod such that it is not fully pointing retrograde; pod and paradock experiencing overheat warnings

So it looks like `ModuleLiftingSurface` is critical to the new aero reentry system, but quite a bit of tweaking will be needed to bring the SDHI heat shield on par with the stock 2.5m one.

**Comment by sumghai** [comment]
@Starwaster - I dun goofed.

If you look at the SDHI Heatshield CFG at any commit up to and including 30e9148, you'll find that there already exists some `CoPOffset` and `CoLOffset` values. In 30e9148, all I did was to add some new definitions at the top, not realizing the old ones were still there.

As of ecda9e1, I've made sure to remove the old values, and also adjusted the `CoMOffset`, since I noticed that the stock heatshield has its CoM based around the centroid of the shield mesh (whereas the centroid for SDHI's heatshield is up from the origin by 0.075m).

In any case, I ran some tests with the latest updated CFG, and it seems to be much more stable at pointing retrograde. Please test this out and let me know if it works okay.

**Comment by Starwaster** [comment]
looks good so far.

**Comment by sumghai** [comment]
**Bomoo** also reports that it works on his end too, so I think we can wrap this one up.
