### ISSUE TITLE
Regression & Dependency Testing for SDHI SMS v3.1.1 on KSP 1.1 prerelease

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#90]
### Regression testing of basic features with mandatory depedencies
Set up a copy of the game with the following installed in GameData:
 - SDHI SMS release candidate
 - Animated Decouplers plugin prerelease for KSP 1.1 (Starwaster)
 - RealChute plugin v1.4x3 (stupid_chris)
 - Module Manager v2.6.21 (sarbian)
 - HyperEdit beta 3 v1.1 (Ezriilc)

Assemble a basic SDHI SMS stack:
 - Use stock solar panels and RCS thrusters on the Service Module
 - Disable the shrouds on the **LV-909 "Terrier" Liquid Engine** before attaching the adapter
 - First stage should consist of a **Rockomax Jumbo-64 Fuel Tank** and a **Rockomax "Mainsail" Liquid Engine**

Test results:
- **Basic SDHI SMS stack assembly**
 - [x] Parts assembled with little to no difficulty
 - [x] Umbilical port retrofit on Mk1-2 Pod can be enabled in VAB/SPH editor scene
 - [x] Staging icons appear and are correct
 - [x] Action Group editor for RealChutes PartModule on docking ports are disabled
- **Pad abort test**
 - [x] Mk1-2 Pod decouples from SM module after umbilical animation plays out in full
 - [x] LES lifts Mk1-2 Pod away from rocket cleanly to an altitude of at least 1 km
 - [x] LES can be steered using integral SolidFuel RCS thruster
 - [x] Mk1-2 Pod shroud jettisoned at apex of trajectory with no issues
 - [x] Parachute lands Mk1-2 Pod safely at ~6 m/s
- **In-flight abort test**
 - [x] Rocket reaches altitude of at least 2 km before triggering abort
 - [x] Mk1-2 Pod decouples from SM module after umbilical animation plays out in full
 - [x] LES lifts Mk1-2 Pod away from rocket cleanly
 - [x] LES can be steered using integral SolidFuel RCS thruster
 - [x] Mk1-2 Pod shroud jettisoned at apex of trajectory with no issues
 - [x] Parachute lands Mk1-2 Pod safely at ~6 m/s
- **Orbital testing (100 km circular orbit using HyperEdit)**
 - [x] Solar Panels and RCS thrusters non-operable while side fairings are intact
 - [x] LES, Mk1-2 Pod shroud and side fairings jettisoned via normal staging with no issues
 - [x] Solar Panels and RCS thrusters operational after side fairings jettison via staging
 - [x] SM adapter decouples from SM with no issues
 - [x] Fairingless LV-909 engine operates with no issues
- **Atmospheric re-entry (ballistic trajectory)**
 - [x] Mk1-2 Pod decouples from SM module after umbilical animation plays out in full
 - [x] Mk1-2 Pod, parachute-equipped docking port and heat shield survives re-entry with acceptable losses in Abalative Shielding
 - [x] Parachute lands Mk1-2 Pod safely at ~6 m/s

### Regression testing of additional features with supported add-ons

- **Deadly Reentry Continued plugin v7.4.0 prerelease for KSP 1.1 (NathanKell / Starwaster)**
 - [x] Mk1-2 Pod, parachute-equipped docking port and heat shield survives re-entry with acceptable losses in Abalative Shielding
 - [x] Other SMS components are destroyed during re-entry
- **TAC Life Support plugin v0.11.2.1 (TaranisElsu)**
 - *Testing currently not possible as plugin has not been updated for KSP 1.0.5*
- **Ship Manifest plugin v 5.0.9.0 and Connected Living Spaces API plugin v1.2.0.9 for KSP 1.1 prerelease (Papa_Joe)**
 - [x] Crew can be transferred through both docking port variants

**Comment by sumghai** [comment]
As it stands right now, the basic features of SDHI SMS v3.1.1 work properly in the KSP 1.1 prerelease, and so publishing a beta release of this mod should be kosher while we wait for the supported add-ons to be updated.

**Comment by SebFierce** [comment]
**Test results:**

**Basic SDHI SMS stack assembly**
- Parts assembled with little to no difficulty - no difficulty at all
- Umbilical port retrofit on Mk1-2 Pod can be enabled in VAB/SPH editor scene - even with most recent Beta this can't be done, option doesn't appear
- Staging icons appear and are correct - all working perfectly
- Action Group editor for RealChutes PartModule on docking ports are disabled - yes the RealChute configurator is disabled for both docking ports

**Pad abort test**
- Mk1-2 Pod decouples from SM module after umbilical animation plays out in full - works well, takes a bit of getting used to though, you hit Backspace, the LES fires but CM doesn't decouple for a short moment
- LES lifts Mk1-2 Pod away from rocket cleanly to an altitude of at least 1 km - it does, CM can be landed save and sound from 0 0 conditions
- LES can be steered using integral SolidFuel RCS thruster - it can be steered, due to the long lever the steering is over sensitive though
- Mk1-2 Pod shroud jettisoned at apex of trajectory with no issues - no problems here, can be jettisoned in various other positions too
- Parachute lands Mk1-2 Pod safely at ~6 m/s - lands at 6,6m/s, save and sound

**In-flight abort test**
- Rocket reaches altitude of at least 2 km before triggering abort - check
- Mk1-2 Pod decouples from SM module after umbilical animation plays out in full - check
- LES lifts Mk1-2 Pod away from rocket cleanly - check
- LES can be steered using integral SolidFuel RCS thruster - check
- Mk1-2 Pod shroud jettisoned at apex of trajectory with no issues - check
- Parachute lands Mk1-2 Pod safely at ~6 m/s - check

**Orbital testing (100 km circular orbit using HyperEdit)**
- Solar Panels and RCS thrusters non-operable while side fairings are intact - works perfect
- LES, Mk1-2 Pod shroud and side fairings jettisoned via normal staging with no issues - works well too, side fairings decouplers are a bit too forceful in my opinion
- Solar Panels and RCS thrusters operational after side fairings jettison via staging - yes they are
- SM adapter decouples from SM with no issues - works perfect
- Fairingless LV-909 engine operates with no issues - perfect too, no issues

**Atmospheric re-entry (ballistic trajectory)**
- Mk1-2 Pod decouples from SM module after umbilical animation plays out in full - check, decoupler force is too strong though, lowers my periapsis from 25km to 19km when activated 80km high, coming from a 100km circular orbit.
- Mk1-2 Pod, parachute-equipped docking port and heat shield survives re-entry with acceptable losses in Abalative Shielding - check, on 120% heat setting between 150 and 200 ablator are lost, depending on trajectory
- Parachute lands Mk1-2 Pod safely at ~6 m/s - check, if parachute is armed in space, drogues activate too early and get ripped off, drogues also slow the CM too hard with 15+g of torgue

I did this test on the Windows 64bit version, no crashes, error messages, lags, stutter, nothing. Appears as if this finally works :D

**Comment by sumghai** [comment]
Just retested everything in the public release of KSP 1.1, including the supported add-ons. All is well.

Looks like we're ready for prime time!
